language: python
sudo: required
notifications:
  email: false

python:
- '2.7'
- '3.6'
before_install:
- sudo apt-get -y install gcc libattr1-dev
script:
  - make check TEST_TARGET=./tests/
deploy:
  provider: pypi

after_deploy:
- make rpm
